# Raw data analysis

## Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Load data

In [2]:
data_path = "../../../data/Hourly_Electricity_Demand_Gen_Weather_Spain/{}.csv";

energy_data_path = data_path.format("energy_dataset");
weather_data_path = data_path.format("weather_features");

In [3]:
energy_data = pd.read_csv(energy_data_path);
weather_data = pd.read_csv(weather_data_path);

## Basic analysis

In [4]:
energy_data.head()

,time,generation biomass,generation fossil brown coal/lignite,generation fossil coal-derived gas,generation fossil gas,generation fossil hard coal,generation fossil oil,generation fossil oil shale,generation fossil peat,generation geothermal,...,generation waste,generation wind offshore,generation wind onshore,forecast solar day ahead,forecast wind offshore eday ahead,forecast wind onshore day ahead,total load forecast,total load actual,price day ahead,price actual
0,2015-01-01 00:00:00+01:00,447.0,329.0,0.0,4844.0,4821.0,162.0,0.0,0.0,0.0,...,196.0,0.0,6378.0,17.0,NaN,6436.0,26118.0,25385.0,50.10,65.41
1,2015-01-01 01:00:00+01:00,449.0,328.0,0.0,5196.0,4755.0,158.0,0.0,0.0,0.0,...,195.0,0.0,5890.0,16.0,NaN,5856.0,24934.0,24382.0,48.10,64.92
2,2015-01-01 02:00:00+01:00,448.0,323.0,0.0,4857.0,4581.0,157.0,0.0,0.0,0.0,...,196.0,0.0,5461.0,8.0,NaN,5454.0,23515.0,22734.0,47.33,64.48
3,2015-01-01 03:00:00+01:00,438.0,254.0,0.0,4314.0,4131.0,160.0,0.0,0.0,0.0,...,191.0,0.0,5238.0,2.0,NaN,5151.0,22642.0,21286.0,42.27,59.32
4,2015-01-01 04:00:00+01:00,428.0,187.0,0.0,4130.0,3840.0,156.0,0.0,0.0,0.0,...,189.0,0.0,4935.0,9.0,NaN,4861.0,21785.0,20264.0,38.41,56.04

In [5]:
energy_data.info();

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 29 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   time                                         35064 non-null  object
 1   generation biomass                           35045 non-null  float64
 2   generation fossil brown coal/lignite         35046 non-null  float64
 3   generation fossil coal-derived gas           35046 non-null  float64
 4   generation fossil gas                        35046 non-null  float64
 5   generation fossil hard coal                  35046 non-null  float64
 6   generation fossil oil                        35045 non-null  float64
 7   generation fossil oil shale                  35046 non-null  float64
 8   generation fossil peat                       35046 non-null  float64
 9   generation geothermal                        35046 non-null  float64
 10  generation hydro pumped storage aggregated   0 non-null      float64
 11  generation hydro pumped storage consumption  35045 non-null  float64
 12  generation hydro run-of-river and poundage   35045 non-null  float64
 13  generation hydro water reservoir             35046 non-null  float64
 14  generation marine                            35045 non-null  float64
 15  generation nuclear                           35047 non-null  float64
 16  generation other                             35046 non-null  float64
 17  generation other renewable                   35046 non-null  float64
 18  generation solar                             35046 non-null  float64
 19  generation waste                             35045 non-null  float64
 20  generation wind offshore                     35046 non-null  float64
 21  generation wind onshore                      35046 non-null  float64
 22  forecast solar day ahead                     35064 non-null  float64
 23  forecast wind offshore eday ahead            0 non-null      float64
 24  forecast wind onshore day ahead              35064 non-null  float64
 25  total load forecast                          35064 non-null  float64
 26  total load actual                            35028 non-null  float64
 27  price day ahead                              35064 non-null  float64
 28  price actual                                 35064 non-null  float64
dtypes: float64(28), object(1)
memory usage: 7.8+ MB

In [6]:
energy_data.isna().sum()

time                                               0
generation biomass                                19
generation fossil brown coal/lignite              18
generation fossil coal-derived gas                18
generation fossil gas                             18
generation fossil hard coal                       18
generation fossil oil                             19
generation fossil oil shale                       18
generation fossil peat                            18
generation geothermal                             18
generation hydro pumped storage aggregated     35064
generation hydro pumped storage consumption       19
generation hydro run-of-river and poundage        19
generation hydro water reservoir                  18
generation marine                                 19
generation nuclear                                17
generation other                                  18
generation other renewable                        18
generation solar                                  18
generation waste                                  19
generation wind offshore                          18
generation wind onshore                           18
forecast solar day ahead                           0
forecast wind offshore eday ahead              35064
forecast wind onshore day ahead                    0
total load forecast                                0
total load actual                                 36
price day ahead                                    0
price actual                                       0
dtype: int64

In [7]:
energy_data.isna().sum().sum()

70529

Timestamp is not properly formatted. Two columns consist only of null values, and will therefore be dropped. Some missing values here and there, but nothing too serious, it seems.

In [8]:
weather_data.head()

,dt_iso,city_name,temp,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,rain_1h,rain_3h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,2015-01-01 00:00:00+01:00,Valencia,270.475,270.475,270.475,1001,77,1,62,0.0,0.0,0.0,0,800,clear,sky is clear,01n
1,2015-01-01 01:00:00+01:00,Valencia,270.475,270.475,270.475,1001,77,1,62,0.0,0.0,0.0,0,800,clear,sky is clear,01n
2,2015-01-01 02:00:00+01:00,Valencia,269.686,269.686,269.686,1002,78,0,23,0.0,0.0,0.0,0,800,clear,sky is clear,01n
3,2015-01-01 03:00:00+01:00,Valencia,269.686,269.686,269.686,1002,78,0,23,0.0,0.0,0.0,0,800,clear,sky is clear,01n
4,2015-01-01 04:00:00+01:00,Valencia,269.686,269.686,269.686,1002,78,0,23,0.0,0.0,0.0,0,800,clear,sky is clear,01n

In [9]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178396 entries, 0 to 178395
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dt_iso               178396 non-null  object
 1   city_name            178396 non-null  object
 2   temp                 178396 non-null  float64
 3   temp_min             178396 non-null  float64
 4   temp_max             178396 non-null  float64
 5   pressure             178396 non-null  int64
 6   humidity             178396 non-null  int64
 7   wind_speed           178396 non-null  int64
 8   wind_deg             178396 non-null  int64
 9   rain_1h              178396 non-null  float64
 10  rain_3h              178396 non-null  float64
 11  snow_3h              178396 non-null  float64
 12  clouds_all           178396 non-null  int64
 13  weather_id           178396 non-null  int64
 14  weather_main         178396 non-null  object
 15  weather_description  178396 non-null  object
 16  weather_icon         178396 non-null  object
dtypes: float64(6), int64(6), object(5)
memory usage: 23.1+ MB

Timestamp is not properly formatted. There appear to be no missing values.

## Miscellaneous checks

In [10]:
pd.to_datetime(energy_data.time)

C:\Users\ml4\AppData\Local\Temp\ipykernel_14248\2531640596.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  pd.to_datetime(energy_data.time)

0        2015-01-01 00:00:00+01:00
1        2015-01-01 01:00:00+01:00
2        2015-01-01 02:00:00+01:00
3        2015-01-01 03:00:00+01:00
4        2015-01-01 04:00:00+01:00
                   ...
35059    2018-12-31 19:00:00+01:00
35060    2018-12-31 20:00:00+01:00
35061    2018-12-31 21:00:00+01:00
35062    2018-12-31 22:00:00+01:00
35063    2018-12-31 23:00:00+01:00
Name: time, Length: 35064, dtype: object

In [11]:
energy_data.loc[energy_data.time.str.contains("+01:00", regex=False), "time"].count()

14400

In [12]:
energy_data.loc[energy_data.time.str.contains("+02:00", regex=False), "time"].count()

20664

In [13]:
energy_data.shape

(35064, 29)

In [14]:
weather_data.loc[weather_data.dt_iso.str.contains("+01:00", regex=False), "dt_iso"].count()

73947

In [15]:
weather_data.loc[weather_data.dt_iso.str.contains("+02:00", regex=False), "dt_iso"].count()

104449

In [16]:
weather_data.shape

(178396, 17)

The data comprises multiple time zones. Data points from different time zones may have to be treated differently.

In [26]:
energy_data.loc[energy_data.time.str.contains("+01:00", regex=False), "time"].head()

0    2015-01-01 00:00:00+01:00
1    2015-01-01 01:00:00+01:00
2    2015-01-01 02:00:00+01:00
3    2015-01-01 03:00:00+01:00
4    2015-01-01 04:00:00+01:00
Name: time, dtype: object

In [27]:
energy_data.loc[energy_data.time.str.contains("+01:00", regex=False), "time"].tail()

35059    2018-12-31 19:00:00+01:00
35060    2018-12-31 20:00:00+01:00
35061    2018-12-31 21:00:00+01:00
35062    2018-12-31 22:00:00+01:00
35063    2018-12-31 23:00:00+01:00
Name: time, dtype: object

In [31]:
energy_data.loc[energy_data.time.str.contains("+02:00", regex=False), "time"].head()

2090    2015-03-29 03:00:00+02:00
2091    2015-03-29 04:00:00+02:00
2092    2015-03-29 05:00:00+02:00
2093    2015-03-29 06:00:00+02:00
2094    2015-03-29 07:00:00+02:00
Name: time, dtype: object

In [32]:
energy_data.loc[energy_data.time.str.contains("+02:00", regex=False), "time"].tail()

33501    2018-10-27 22:00:00+02:00
33502    2018-10-27 23:00:00+02:00
33503    2018-10-28 00:00:00+02:00
33504    2018-10-28 01:00:00+02:00
33505    2018-10-28 02:00:00+02:00
Name: time, dtype: object

In [33]:
weather_data.loc[weather_data.dt_iso.str.contains("+01:00", regex=False), "dt_iso"].head()

0    2015-01-01 00:00:00+01:00
1    2015-01-01 01:00:00+01:00
2    2015-01-01 02:00:00+01:00
3    2015-01-01 03:00:00+01:00
4    2015-01-01 04:00:00+01:00
Name: dt_iso, dtype: object

In [34]:
weather_data.loc[weather_data.dt_iso.str.contains("+01:00", regex=False), "dt_iso"].tail()

178391    2018-12-31 19:00:00+01:00
178392    2018-12-31 20:00:00+01:00
178393    2018-12-31 21:00:00+01:00
178394    2018-12-31 22:00:00+01:00
178395    2018-12-31 23:00:00+01:00
Name: dt_iso, dtype: object

In [35]:
weather_data.loc[weather_data.dt_iso.str.contains("+02:00", regex=False), "dt_iso"].head()

2091    2015-03-29 03:00:00+02:00
2092    2015-03-29 04:00:00+02:00
2093    2015-03-29 05:00:00+02:00
2094    2015-03-29 06:00:00+02:00
2095    2015-03-29 07:00:00+02:00
Name: dt_iso, dtype: object

In [36]:
weather_data.loc[weather_data.dt_iso.str.contains("+02:00", regex=False), "dt_iso"].tail()

176771    2018-10-27 22:00:00+02:00
176772    2018-10-27 23:00:00+02:00
176773    2018-10-28 00:00:00+02:00
176774    2018-10-28 01:00:00+02:00
176775    2018-10-28 02:00:00+02:00
Name: dt_iso, dtype: object

In [77]:
pd.to_datetime(energy_data.loc[energy_data.time.str.contains("2015-03-29"), "time"], utc=True)

2088   2015-03-28 23:00:00+00:00
2089   2015-03-29 00:00:00+00:00
2090   2015-03-29 01:00:00+00:00
2091   2015-03-29 02:00:00+00:00
2092   2015-03-29 03:00:00+00:00
2093   2015-03-29 04:00:00+00:00
2094   2015-03-29 05:00:00+00:00
2095   2015-03-29 06:00:00+00:00
2096   2015-03-29 07:00:00+00:00
2097   2015-03-29 08:00:00+00:00
2098   2015-03-29 09:00:00+00:00
2099   2015-03-29 10:00:00+00:00
2100   2015-03-29 11:00:00+00:00
2101   2015-03-29 12:00:00+00:00
2102   2015-03-29 13:00:00+00:00
2103   2015-03-29 14:00:00+00:00
2104   2015-03-29 15:00:00+00:00
2105   2015-03-29 16:00:00+00:00
2106   2015-03-29 17:00:00+00:00
2107   2015-03-29 18:00:00+00:00
2108   2015-03-29 19:00:00+00:00
2109   2015-03-29 20:00:00+00:00
2110   2015-03-29 21:00:00+00:00
Name: time, dtype: datetime64[ns, UTC]

Daylight saving time must be accounted for in both datasets.

In [80]:
energy_data.loc[energy_data["total load actual"].isna()]

,time,generation biomass,generation fossil brown coal/lignite,generation fossil coal-derived gas,generation fossil gas,generation fossil hard coal,generation fossil oil,generation fossil oil shale,generation fossil peat,generation geothermal,...,generation waste,generation wind offshore,generation wind onshore,forecast solar day ahead,forecast wind offshore eday ahead,forecast wind onshore day ahead,total load forecast,total load actual,price day ahead,price actual
108,2015-01-05 12:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3932.0,NaN,9258.0,23209.0,NaN,35.50,79.14
109,2015-01-05 13:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4236.0,NaN,9156.0,23725.0,NaN,36.80,73.95
110,2015-01-05 14:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4215.0,NaN,9072.0,23614.0,NaN,32.50,71.93
111,2015-01-05 15:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4050.0,NaN,8779.0,22381.0,NaN,30.00,71.50
112,2015-01-05 16:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3728.0,NaN,8426.0,21371.0,NaN,30.00,71.85
113,2015-01-05 17:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3175.0,NaN,7946.0,20760.0,NaN,30.60,80.53
661,2015-01-28 13:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4136.0,NaN,6223.0,36239.0,NaN,65.00,77.62
751,2015-02-01 07:00:00+01:00,449.0,312.0,0.0,4765.0,5269.0,222.0,0.0,0.0,0.0,...,208.0,0.0,3289.0,18.0,NaN,3141.0,24379.0,NaN,56.10,16.98
752,2015-02-01 08:00:00+01:00,453.0,312.0,0.0,4938.0,5652.0,288.0,0.0,0.0,0.0,...,207.0,0.0,3102.0,63.0,NaN,3165.0,27389.0,NaN,57.69,19.56
753,2015-02-01 09:00:00+01:00,452.0,302.0,0.0,4997.0,5770.0,296.0,0.0,0.0,0.0,...,204.0,0.0,2838.0,691.0,NaN,2907.0,30619.0,NaN,60.01,23.13
756,2015-02-01 12:00:00+01:00,405.0,317.0,0.0,5247.0,6008.0,333.0,0.0,0.0,0.0,...,200.0,0.0,1413.0,3568.0,NaN,1486.0,31357.0,NaN,59.97,22.51
757,2015-02-01 13:00:00+01:00,402.0,317.0,0.0,5449.0,6005.0,318.0,0.0,0.0,0.0,...,193.0,0.0,1347.0,3572.0,NaN,1267.0,31338.0,NaN,59.69,23.44
758,2015-02-01 14:00:00+01:00,400.0,317.0,0.0,5266.0,5995.0,327.0,0.0,0.0,0.0,...,199.0,0.0,1345.0,3474.0,NaN,1363.0,30874.0,NaN,58.69,24.10
759,2015-02-01 15:00:00+01:00,393.0,321.0,0.0,5209.0,5939.0,345.0,0.0,0.0,0.0,...,204.0,0.0,1487.0,2935.0,NaN,1426.0,30124.0,NaN,58.13,21.12
760,2015-02-01 16:00:00+01:00,413.0,325.0,0.0,5642.0,6000.0,345.0,0.0,0.0,0.0,...,203.0,0.0,1648.0,2383.0,NaN,1678.0,29714.0,NaN,59.00,21.73
761,2015-02-01 17:00:00+01:00,465.0,321.0,0.0,6127.0,5912.0,346.0,0.0,0.0,0.0,...,207.0,0.0,1857.0,1211.0,NaN,1807.0,29801.0,NaN,59.69,25.93
762,2015-02-01 18:00:00+01:00,482.0,326.0,0.0,7386.0,6002.0,340.0,0.0,0.0,0.0,...,208.0,0.0,1864.0,392.0,NaN,2050.0,32257.0,NaN,63.76,54.13
763,2015-02-01 19:00:00+01:00,474.0,326.0,0.0,7963.0,6026.0,343.0,0.0,0.0,0.0,...,207.0,0.0,1813.0,98.0,NaN,1933.0,33183.0,NaN,65.01,68.53
2258,2015-04-05 03:00:00+02:00,371.0,0.0,0.0,5015.0,3248.0,257.0,0.0,0.0,0.0,...,142.0,0.0,3153.0,55.0,NaN,3026.0,20016.0,NaN,42.55,29.04
2528,2015-04-16 09:00:00+02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,952.0,NaN,3377.0,31001.0,NaN,56.54,67.55
2623,2015-04-20 08:00:00+02:00,424.0,642.0,0.0,5614.0,5784.0,369.0,0.0,0.0,0.0,...,147.0,0.0,797.0,692.0,NaN,830.0,29287.0,NaN,62.00,72.92
2708,2015-04-23 21:00:00+02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,327.0,NaN,1058.0,31421.0,NaN,69.49,82.57
2913,2015-05-02 10:00:00+02:00,497.0,0.0,0.0,5502.0,5677.0,375.0,0.0,0.0,0.0,...,205.0,0.0,10903.0,2277.0,NaN,11069.0,39644.0,NaN,58.49,59.09
3554,2015-05-29 03:00:00+02:00,569.0,756.0,0.0,4239.0,4635.0,365.0,0.0,0.0,0.0,...,201.0,0.0,6503.0,554.0,NaN,6355.0,23132.0,NaN,45.93,55.07
6583,2015-10-02 08:00:00+02:00,483.0,961.0,0.0,6545.0,8250.0,385.0,0.0,0.0,0.0,...,205.0,0.0,4362.0,185.0,NaN,4404.0,36798.0,NaN,66.19,70.13
6586,2015-10-02 11:00:00+02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2513.0,NaN,3690.0,38921.0,NaN,70.09,70.49
8049,2015-12-02 09:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,684.0,NaN,1510.0,37413.0,NaN,75.71,80.44
11524,2016-04-25 05:00:00+02:00,190.0,0.0,0.0,2969.0,886.0,151.0,0.0,0.0,0.0,...,195.0,0.0,5989.0,412.0,NaN,6019.0,21471.0,NaN,15.00,22.65
11526,2016-04-25 07:00:00+02:00,206.0,0.0,0.0,3673.0,1143.0,185.0,0.0,0.0,0.0,...,214.0,0.0,5682.0,208.0,NaN,5758.0,27635.0,NaN,32.97,40.18
11902,2016-05-10 23:00:00+02:00,348.0,960.0,0.0,6800.0,5219.0,299.0,0.0,0.0,0.0,...,280.0,0.0,3311.0,84.0,NaN,3465.0,26641.0,NaN,51.57,39.11
13341,2016-07-09 22:00:00+02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,499.0,NaN,4914.0,34985.0,NaN,45.72,51.72
15272,2016-09-28 09:00:00+02:00,347.0,594.0,0.0,5522.0,6272.0,292.0,0.0,0.0,0.0,...,300.0,0.0,5478.0,967.0,NaN,5359.0,31072.0,NaN,49.72,56.40
25164,2017-11-14 12:00:00+01:00,0.0,0.0,0.0,10064.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4325.0,NaN,7561.0,33805.0,NaN,60.53,66.17
25171,2017-11-14 19:00:00+01:00,0.0,0.0,0.0,12336.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,128.0,NaN,5679.0,35592.0,NaN,68.05,75.45
30185,2018-06-11 18:00:00+02:00,331.0,506.0,0.0,7538.0,5360.0,300.0,0.0,0.0,0.0,...,269.0,0.0,9165.0,125.0,NaN,10329.0,34752.0,NaN,69.87,64.93
30896,2018-07-11 09:00:00+02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,849.0,NaN,9956.0,33938.0,NaN,63.01,69.79